SEEN_MAX = 1500
EXTRINSIC_START_CALL = 'START_CALL'
EXTRINSIC_SUBMIT_ENCRYPTED = 'SUBMIT_ENCRYPTED'
WHITELISTED_SUBNETS = [40, 58]
BLACK_LISTED_COLDKEYS = ["5F9Qvcz22Fwq4cm58o2bShiL6n8BnJmhqXB1cispBpqRfN6w"]
STAKE_AMOUNT_TAO = 1